#!/bin/bash
# This script is used to configure and run Consul.

set -e

readonly CONSUL_CONFIG_FILE="default.json"
readonly SUPERVISOR_CONFIG_PATH="/etc/supervisor/conf.d/run-consul.conf"

readonly DEFAULT_RAFT_PROTOCOL="3"

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_NAME="$(basename "$0")"

function print_usage {
  echo
  echo "Usage: run-consul [OPTIONS]"
  echo
  echo "This script is used to configure and run Consul."
  echo
  echo "Required Arguments:"
  echo
  echo -e "  --server\t\tIf set, run in server mode. Exactly one of --server or --client must be set."
  echo -e "  --client\t\tIf set, run in client mode. Exactly one of --server or --client must be set."
  echo
  echo "Optional Arguments:"
  echo
  echo -e "  --datacenter\tConsul cluster datacenter."
  echo -e "  --retry-join\tConsul retry join to one or more agent IPs."
  echo -e "  --bootstrap\tConsul bootstrap node count to expect."
  echo -e "  --raft-protocol\tThis controls the internal version of the Raft consensus protocol used for server "
  echo -e "                 \tcommunications. Must be set to 3 in order to gain access to Autopilot features, with the"
  echo -e "                 \texception of cleanup_dead_servers. Default: $DEFAULT_RAFT_PROTOCOL"
  echo -e "  --config-dir\t\tThe path to the Consul config folder. Default is the absolute path of '../config', relative to this script."
  echo -e "  --data-dir\t\tThe path to the Consul data folder. Default is the absolute path of '../data', relative to this script."
  echo -e "  --log-dir\t\tThe path to the Consul log folder. Default is the absolute path of '../log', relative to this script."
  echo -e "  --bin-dir\t\tThe path to the folder with Consul binary. Default is the absolute path of the parent folder of this script."
  echo -e "  --user\t\tThe user to run Consul as. Default is to use the owner of --config-dir."
  echo -e "  --skip-consul-config\tIf this flag is set, don't generate a Consul configuration file. Default is false."
  echo
  echo "Example:"
  echo
  echo "  run-consul --server --datacenter dc1 --config-dir /custom/path/to/consul/config"
}

function log {
  local readonly level="$1"
  local readonly message="$2"
  local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
}

function log_info {
  local readonly message="$1"
  log "INFO" "$message"
}

function log_warn {
  local readonly message="$1"
  log "WARN" "$message"
}

function log_error {
  local readonly message="$1"
  log "ERROR" "$message"
}

# Based on code from: http://stackoverflow.com/a/16623897/483528
function strip_prefix {
  local readonly str="$1"
  local readonly prefix="$2"
  echo "${str#$prefix}"
}

function assert_is_installed {
  local readonly name="$1"

  if [[ ! $(command -v ${name}) ]]; then
    log_error "The binary '$name' is required by this script but is not installed or in the system's PATH."
    exit 1
  fi
}

function assert_not_empty {
  local readonly arg_name="$1"
  local readonly arg_value="$2"

  if [[ -z "$arg_value" ]]; then
    log_error "The value for '$arg_name' cannot be empty"
    print_usage
    exit 1
  fi
}

# Get the IP Address
function get_instance_ip_address {
  ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1
}

function generate_consul_config {
  local readonly server="$1"
  local readonly raft_protocol="$2"
  local readonly config_dir="$3"
  local readonly user="$4"
  local readonly instance_ip_address="$5"
  local readonly cluster_datacenter="$6"
  local readonly cluster_size="$7"
  local readonly cluster_retry_join="$8"
  local readonly config_path="$config_dir/$CONSUL_CONFIG_FILE"

  local instance_name=""

  instance_name=$HOSTNAME

  local retry_join_json=""
  if [[ -z "$cluster_retry_join" ]]; then
    log_warn "The --retry-join property is empty. Will not automatically try to form a cluster."
  else
    retry_join_json="\"retry_join\": [\"$cluster_retry_join\"],"
  fi

  local bootstrap_expect=""

  if [[ "$server" == "true" ]]; then
    bootstrap_expect="\"bootstrap_expect\": $cluster_size,"
  fi

  log_info "Creating default Consul config file in $config_path"
  cat > "$config_path" <<EOF
{
  "advertise_addr": "$instance_ip_address",
  "bind_addr": "$instance_ip_address",
  $bootstrap_expect
  "client_addr": "0.0.0.0",
  "datacenter": "$instance_zone",
  "node_name": "$instance_name",
  $retry_join_json
  "server": $server,
  "ui": true,
  "raft_protocol": $raft_protocol
}
EOF
  chown "$user:$user" "$config_path"
}

function generate_supervisor_config {
  local readonly supervisor_config_path="$1"
  local readonly consul_config_dir="$2"
  local readonly consul_data_dir="$3"
  local readonly consul_log_dir="$4"
  local readonly consul_bin_dir="$5"
  local readonly consul_user="$6"

  log_info "Creating Supervisor config file to run Consul in $supervisor_config_path"
  cat > "$supervisor_config_path" <<EOF
[program:consul]
command=$consul_bin_dir/consul agent -config-dir $consul_config_dir -data-dir $consul_data_dir
stdout_logfile=$consul_log_dir/consul-stdout.log
stderr_logfile=$consul_log_dir/consul-error.log
numprocs=1
autostart=true
autorestart=true
stopsignal=INT
user=$consul_user
EOF
}

function start_consul {
  log_info "Reloading Supervisor config and starting Consul"
  supervisorctl reread
  supervisorctl update
}

# Based on: http://unix.stackexchange.com/a/7732/215969
function get_owner_of_path {
  local readonly path="$1"
  ls -ld "$path" | awk '{print $3}'
}

function run {
  local server="false"
  local client="false"
  local raft_protocol="$DEFAULT_RAFT_PROTOCOL"
  local cluster_datacenter=""
  local cluster_size=""
  local cluster_retry_join=""
  local config_dir=""
  local data_dir=""
  local log_dir=""
  local bin_dir=""
  local user=""
  local skip_consul_config="false"
  local all_args=()

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --server)
        server="true"
        ;;
      --client)
        client="true"
        ;;
      --datacenter)
        assert_not_empty "$key" "$2"
        cluster_datacenter="$2"
        shift
        ;;
      --retry-join)
        assert_not_empty "$key" "$2"
        retry_join="$2"
        shift
        ;;
      --bootstrap)
        assert_not_empty "$key" "$2"
        cluster_size="$2"
        shift
        ;;
      --raft-protocol)
        assert_not_empty "$key" "$2"
        raft_protocol="$2"
        shift
        ;;
      --config-dir)
        assert_not_empty "$key" "$2"
        config_dir="$2"
        shift
        ;;
      --data-dir)
        assert_not_empty "$key" "$2"
        data_dir="$2"
        shift
        ;;
      --log-dir)
        assert_not_empty "$key" "$2"
        log_dir="$2"
        shift
        ;;
      --bin-dir)
        assert_not_empty "$key" "$2"
        bin_dir="$2"
        shift
        ;;
      --user)
        assert_not_empty "$key" "$2"
        user="$2"
        shift
        ;;
      --skip-consul-config)
        skip_consul_config="true"
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  if [[ ("$server" == "true" && "$client" == "true") || ("$server" == "false" && "$client" == "false") ]]; then
    log_error "Exactly one of --server or --client must be set."
    exit 1
  fi

  assert_is_installed "supervisorctl"
  assert_is_installed "curl"

  if [[ -z "$config_dir" ]]; then
    config_dir=$(cd "$SCRIPT_DIR/../config" && pwd)
  fi

  if [[ -z "$data_dir" ]]; then
    data_dir=$(cd "$SCRIPT_DIR/../data" && pwd)
  fi

  if [[ -z "$log_dir" ]]; then
    log_dir=$(cd "$SCRIPT_DIR/../log" && pwd)
  fi

  if [[ -z "$bin_dir" ]]; then
    bin_dir=$(cd "$SCRIPT_DIR/../bin" && pwd)
  fi

  if [[ -z "$user" ]]; then
    user=$(get_owner_of_path "$config_dir")
  fi

  if [[ "$skip_consul_config" == "true" ]]; then
    log_info "The --skip-consul-config flag is set, so will not generate a default Consul config file."
  else
    generate_consul_config \
        "$server" \
        "$raft_protocol" \
        "$config_dir" \
        "$user" \
        get_instance_ip_address \
        "$cluster_datacenter"
        "$cluster_size"
        "$cluster_retry_join"
  fi

  generate_supervisor_config "$SUPERVISOR_CONFIG_PATH" "$config_dir" "$data_dir" "$log_dir" "$bin_dir" "$user"
  start_consul
}

run "$@"